#default
build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Ganiyat Lateef"
    email: "ganiyat1425@gmail.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934


