spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
         # search-locations: "classpath:/config"
        #search-locations: "file:///C://dev//eazybank//config"
        git:
          uri: "https://github.com/GaniyatLateef/eazybank_config.git"
          #uri: "https://github.com/GaniyatLateef/spring-cloud-configuration.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB39FF9"

server:
  port: 8071